/**
 * Tests for src/map/pointCloudFormat.js — decoding
 * tools/lidar_pipeline/pointcloud_export.py's binary point cloud format.
 *
 * The primary fixture is REAL bytes produced by the Python packer
 * itself (captured once via `python3 -c "..."` and hardcoded below as a
 * base64 blob), not a hand-encoded buffer — the point of this suite is
 * confirming the JS decoder agrees with the actual Python writer, not
 * that the decoder agrees with its own understanding of the spec.
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import { decodePointCloud } from '../../src/map/pointCloudFormat.js';

// Generated by:
//   python3 -c "
//   from tools.lidar_pipeline.pointcloud_export import pack_point_cloud
//   import numpy as np, base64
//   lng = np.array([-71.896, -71.895000, 12.3456789])
//   lat = np.array([42.2765, 42.277000, -33.987654])
//   alt = np.array([45.25, 100.0, -5.5], dtype=np.float32)
//   cls = np.array([5, 2, 3], dtype=np.uint8)
//   print(base64.b64encode(pack_point_cloud(lng, lat, alt, cls)).decode())
//   "
const REAL_PYTHON_FIXTURE_B64 = 'VFBUUwEDAAAAQPS2+5QWhQIFAAA1Qij4tvuIGIUCAgAAyEJPYbwAumP5/QMAALDA';

function base64ToArrayBuffer(b64) {
    const binary = Buffer.from(b64, 'base64');
    return binary.buffer.slice(binary.byteOffset, binary.byteOffset + binary.byteLength);
}

describe('decodePointCloud against real Python-packed bytes', () => {
    const buffer = base64ToArrayBuffer(REAL_PYTHON_FIXTURE_B64);
    const decoded = decodePointCloud(buffer);

    test('decodes the correct point count', () => {
        assert.equal(decoded.count, 3);
    });

    test('longitude matches to microdegree quantization', () => {
        const expected = [-71.896, -71.895, 12.3456789];
        for (let i = 0; i < 3; i++) {
            assert.ok(Math.abs(decoded.lng[i] - expected[i]) < 1e-6, `point ${i}: ${decoded.lng[i]} vs ${expected[i]}`);
        }
    });

    test('latitude matches to microdegree quantization', () => {
        const expected = [42.2765, 42.277, -33.987654];
        for (let i = 0; i < 3; i++) {
            assert.ok(Math.abs(decoded.lat[i] - expected[i]) < 1e-6, `point ${i}: ${decoded.lat[i]} vs ${expected[i]}`);
        }
    });

    test('altitude matches to float32 precision', () => {
        const expected = [45.25, 100.0, -5.5];
        for (let i = 0; i < 3; i++) {
            assert.ok(Math.abs(decoded.altitudeM[i] - expected[i]) < 1e-3, `point ${i}: ${decoded.altitudeM[i]} vs ${expected[i]}`);
        }
    });

    test('classification bytes match exactly', () => {
        assert.deepEqual(Array.from(decoded.classification), [5, 2, 3]);
    });
});

describe('error handling', () => {
    test('rejects bad magic', () => {
        const buf = new ArrayBuffer(9);
        const view = new DataView(buf);
        view.setUint8(0, 0x58); view.setUint8(1, 0x58); view.setUint8(2, 0x58); view.setUint8(3, 0x58);
        assert.throws(() => decodePointCloud(buf), /bad magic/);
    });

    test('rejects unsupported version', () => {
        const buf = new ArrayBuffer(9);
        const view = new DataView(buf);
        view.setUint8(0, 84); view.setUint8(1, 80); view.setUint8(2, 84); view.setUint8(3, 83); // "TPTS"
        view.setUint8(4, 99); // version 99
        view.setUint32(5, 0, true);
        assert.throws(() => decodePointCloud(buf), /unsupported version/);
    });

    test('rejects a truncated buffer', () => {
        const buffer = base64ToArrayBuffer(REAL_PYTHON_FIXTURE_B64);
        assert.throws(() => decodePointCloud(buffer.slice(0, buffer.byteLength - 3)), /expected/);
    });

    test('decodes an empty point cloud without error', () => {
        const buf = new ArrayBuffer(9);
        const view = new DataView(buf);
        view.setUint8(0, 84); view.setUint8(1, 80); view.setUint8(2, 84); view.setUint8(3, 83);
        view.setUint8(4, 1);
        view.setUint32(5, 0, true);
        const decoded = decodePointCloud(buf);
        assert.equal(decoded.count, 0);
    });
});
